apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: knxvault-inject
webhooks:
  - name: inject.knxvault.dev
    admissionReviewVersions: ["v1"]
    sideEffects: None
    clientConfig:
      service:
        name: knxvault-webhook
        namespace: knxvault
        path: /mutate
        port: 9443
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
    failurePolicy: Fail
    namespaceSelector:
      matchExpressions:
        - key: knxvault.io/webhook
          operator: In
          values: ["enabled"]