# Copyright Kubenexis Systems Private Limited.
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: knxvault-leader
  namespace: knxvault
  labels:
    app.kubernetes.io/name: knxvault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: knxvault-leader
subjects:
  - kind: ServiceAccount
    name: knxvault
    namespace: knxvault