# Copyright The KNXVault Authors.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  name: knxvault
  namespace: knxvault
  labels:
    app.kubernetes.io/name: knxvault