apiVersion: v1
kind: Service
metadata:
  name: knxvault
  namespace: knxvault
  labels:
    app.kubernetes.io/name: knxvault
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: knxvault
  ports:
    - name: http
      port: 8200
      targetPort: http
      protocol: TCP