# KNXVault Secrets Store CSI provider (W39).
# Requires the Secrets Store CSI Driver: https://secrets-store-csi-driver.sigs.k8s.io/
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: knxvault-csi-provider
  namespace: knxvault
  labels:
    app.kubernetes.io/name: knxvault-csi-provider
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: knxvault-csi-provider
  template:
    metadata:
      labels:
        app.kubernetes.io/name: knxvault-csi-provider
    spec:
      serviceAccountName: knxvault-csi-provider
      containers:
        - name: provider
          image: knxvault:0.5.1
          imagePullPolicy: IfNotPresent
          command: ["/usr/local/bin/knxvault-csi"]
          env:
            - name: KNXVAULT_CSI_SOCKET
              value: /var/run/secrets-store-csi-providers/knxvault.sock
          volumeMounts:
            - name: providervol
              mountPath: /var/run/secrets-store-csi-providers
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
      volumes:
        - name: providervol
          hostPath:
            path: /var/run/secrets-store-csi-providers
            type: DirectoryOrCreate